server:
  port: 8010


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  #表示将自己的IP注册到Eureka Server。若不配置该属性或将其设置为false,
    #则表示注册微服务所在操作系统的hostname到Eureka Server。

spring:
  application:
    name: microservice-consumer-movie-feign-hystrix

feign:
  hystrix:
    enabled: true