security:
  basic:
    enabled: true #开启基于HTTP basic的认证
  user:
    name: user              #配置登录的用户名是user
    password: password123   #配置登录的密码是password123

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/

server:
  port: 8761

